fix: format spacing in jobs action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -9,22 +9,22 @@ on:
 
 jobs:
   rules-tag:
-  runs-on: ubuntu-latest
-  steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Validate SemVer standard
-      run: |
-          TAG_NAME=${GITHUB_REF#refs/tags/} 
-          SEMVER_REGEX="^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
-          
-          if [[ ! $TAG_NAME =~ $SEMVER_REGEX]]; then 
-            echo "Error: Tag $TAG_NAME tidak sesuai dengan standar SemVer!" 
-            exit 1 
-          else 
-            echo "Tag $TAG_NAME valid menggunakan standar SemVer." 
-          fi
+      - name: Validate SemVer standard
+        run: |
+            TAG_NAME=${GITHUB_REF#refs/tags/} 
+            SEMVER_REGEX="^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
+            
+            if [[ ! $TAG_NAME =~ $SEMVER_REGEX]]; then 
+              echo "Error: Tag $TAG_NAME tidak sesuai dengan standar SemVer!" 
+              exit 1 
+            else 
+              echo "Tag $TAG_NAME valid menggunakan standar SemVer." 
+            fi
 
   build-docker-image:
     needs: rules-tag
